"""Constants for Yamaha CRX-N560 integration."""

DOMAIN = "yamaha_crx_n560d"
MODEL = "CRX-N560"
MANUFACTURER = "Yamaha"

DEFAULT_NAME = "Yamaha CRX-N560"
DEFAULT_TIMEOUT = 5

VOLUME_MIN = 0
VOLUME_MAX = 60
MAX_PRESETS = 30

SOURCE_CD = "CD"
SOURCE_TUNER = "TUNER"
SOURCE_AUX1 = "AUX1"
SOURCE_AUX2 = "AUX2"
SOURCE_DIGITAL1 = "DIGITAL1"
SOURCE_DIGITAL2 = "DIGITAL2"
SOURCE_SERVER = "SERVER"
SOURCE_NET_RADIO = "NET RADIO"
SOURCE_USB = "USB"
SOURCE_AIRPLAY = "AirPlay"
SOURCE_SPOTIFY = "Spotify"

AVAILABLE_SOURCES = [
    SOURCE_CD,
    SOURCE_TUNER,
    SOURCE_AUX1,
    SOURCE_AUX2,
    SOURCE_DIGITAL1,
    SOURCE_DIGITAL2,
    SOURCE_SERVER,
    SOURCE_NET_RADIO,
    SOURCE_USB,
    SOURCE_AIRPLAY,
    SOURCE_SPOTIFY,
]

SLEEP_VALUES = ["Off", "30 min", "60 min", "90 min", "120 min"]

SOURCES_WITH_PLAYER = [SOURCE_CD, SOURCE_SERVER, SOURCE_NET_RADIO, SOURCE_USB, SOURCE_AIRPLAY, SOURCE_SPOTIFY]
SOURCES_WITH_SERVER_BROWSE = [SOURCE_SERVER, SOURCE_NET_RADIO]
